In [1]:
import numpy as np

In [22]:
a1 = [1, 2, 3, 4, 5]

a2 = np.array(a1)

print(a1)
print(a2)

# print(a1.ndim)
print(a2.ndim)
# print(a1.shape)
print(a2.shape)
# print(a1.dtype)
print(a2.dtype)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
1
(5,)
int32


In [14]:
b1 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

b2 = np.array(b1)

print(b1)
print(b2)

# print(b1.ndim)
print(b2.ndim)
# print(b1.shape)
print(b2.shape)
# print(b1.dtype)
print(b2.dtype)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
int32


In [26]:
c1 = [[[1, 2, 3], [6, 7, 8], [11, 12, 13]], 
      [[16, 17, 18], [21, 22, 23], [26, 27, 28]],
      [[1, 3, 5], [2, 4, 6], [10, 20, 30]]]

c2 = np.array(c1)

print(c1)
print(c2)

print(c2.ndim)
print(c2.shape)
print(c2.dtype)

[[[1, 2, 3], [6, 7, 8], [11, 12, 13]], [[16, 17, 18], [21, 22, 23], [26, 27, 28]], [[1, 3, 5], [2, 4, 6], [10, 20, 30]]]
[[[ 1  2  3]
  [ 6  7  8]
  [11 12 13]]

 [[16 17 18]
  [21 22 23]
  [26 27 28]]

 [[ 1  3  5]
  [ 2  4  6]
  [10 20 30]]]
3
(3, 3, 3)
int32


[문1] numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [24]:
# 라이브러리 불러오기
import numpy as np

[문2] 다음에 주어진 데이터를 갖는 1차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요.

In [25]:
# 10, 11, 12, 13, 14, 15

# 배열 만들기
a = [10, 11, 12, 13, 14, 15]
b = np.array(a)

# 확인
print(a)

# 정보 확인
print(b.shape)

[10, 11, 12, 13, 14, 15]
(6,)


[문3] 다음에 주어진 리스트를 요소로 갖는 2차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요

In [27]:
a = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

# 배열 만들기
b = np.array(a)

# 확인
print(b)

# 정보 확인
print(b.shape)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
(3, 4)


#### 3) Reshape

- 배열을 사용할 때 다양한 형태(Shape)로 변환할 필요가 있습니다.
- 배열에 포함된 **요소가 사라지지 않는 형태**라면 자유롭게 변환할 수 있습니다.
- (3, 4) → (2, 6) → (4, 3) → (12, 1) → (6, 2) 등등 요소 개수만 변하지 않으면 됩니다.

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

[[1 2 3]
 [4 5 6]]


**1) (2, 3) → (3, 2)**

In [30]:
# (3, 2) 형태의 2차원 배열로 Reshape
b = a.reshape(3, 2)

# 확인
print(b)

[[1 2]
 [3 4]
 [5 6]]


**2) (2, 3) → (6,)**

In [31]:
# 1차원 배열로 reshape
# c = a.reshape(6,)

c = a.reshape(6)

print(c)

[1 2 3 4 5 6]


In [32]:
# 1차원 배열로 reshape
c = a.reshape(6,)

# c = a.reshape(6)

print(c)

[1 2 3 4 5 6]


**3) -1의 편리성**

- **(*m*, -1)** 또는 **(-1, *n*)** 처럼 사용해 행 또는 열 크기 한 쪽만 지정할 수 있습니다.

In [33]:
# (2 ,3) 형태의 2차원 배열 만들기

a = np.array([[1, 2, 3], [4, 5, 6]])

# 확인
print(a)

[[1 2 3]
 [4 5 6]]


In [35]:
# reshape(m, -1) 형태로 지정하여 Reshape 가능, 약수만 가능(point)

print(a.reshape(1, -1))
print()

print(a.reshape(2, -1))
print()

print(a.reshape(3, -1))
print()

#print(a.reshape(4, -1))
#print(a.reshape(5, -1))

print(a.reshape(6, -1))
print()

[[1 2 3 4 5 6]]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]



<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음에 주어진 배열의 형태(shape)를 확인한 후 요구되는 형태로 바꿔 보세요.

In [40]:
# 배열 만들기
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

# 배열 형태 확인
print(a.shape)

# (4, ?) 형태의 2차원 배열
b = a.reshape(4, -1)

# 확인
print(b)

# (2, ?) 형태의 2차원 배열
c = a.reshape(2, -1)

# 확인
print(c)

(3, 4)
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[11 12 13 14 15 16]
 [17 18 19 20 21 22]]


In [41]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 확인
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**1) 요소 조회**

In [43]:
# 첫 번째 행, 두 번째 열 요소 조회
print(a[0, 1])

2


**2) 행 조회**

In [44]:
# 첫 번째, 두 번째 행 조회
# print(a[[0, 1], :])

print(a[[0, 1]])

[[1 2 3]
 [4 5 6]]


In [60]:
# 첫 번째, 두 번째 행 조회
print(a[[0, 1], :])

# print(a[[0, 1]])

[[11 12 13 14]
 [15 16 17 18]]


In [64]:
# 첫 번째, 두 번째, 세 번째 행 조회
# print(a[[0, 1, 2], :])
print(a[[0, 1, 2]])

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [65]:
# 첫 번째, 두 번째, 세 번째 행 조회
print(a[[0, 1, 2], :])
# print(a[0, 1, 2])

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


**3) 열 조회**

In [46]:
# 첫 번째, 두 번째 열 조회
print(a[:, [0, 1]])

[[1 2]
 [4 5]
 [7 8]]


**4) 행, 열 조회**

In [48]:
# 배열 확인
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
# 두 번째 행 두 번째 열의 조회
print(a[1][1])
print(a[[1], [1]])

5
[5]


In [52]:
# 세 번째 행 두 번째 열의 조회
print(a[2][1])
print(a[[2], [1]])

8
[8]


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [53]:
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

[문1] 16

In [76]:
print(a[1][1])
print(a[1, 1])
print(a[[1], [1]])

16
16
[16]


[문2] [19 20 21 22]

In [77]:
print(a[2][:])
print(a[2, :])
print(a[[2], :])

[19 20 21 22]
[19 20 21 22]
[[19 20 21 22]]


[문3] [13  17  21]

In [78]:
print(a[:][2])
print(a[:, 2])
print(a[:, [2]])

[19 20 21 22]
[13 17 21]
[[13]
 [17]
 [21]]


### (2) 슬라이싱

- **배열[행1:행N,열1:열N]** 형태로 지정해 그 위치의 요소를 조회합니다.
- 조회 결과는 **2차원 배열**이 됩니다.
- 마지막 **범위 값은 대상에 포함되지 않습니다.**
- 즉, **배열[1:M, 2:N]**이라면 1 ~ M-1행, 2 ~ N-1열이 조회 대상이 됩니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [79]:
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

[문1]   

[[12  
16  
20]

In [97]:
a[:,1:2]

array([[12],
       [16],
       [20]])

[문2] 

[[16  17]  
 [20  21]]

In [95]:
a[1:,1:3]

array([[16, 17],
       [20, 21]])

In [98]:
a[[1, 2], 1:3]

array([[16, 17],
       [20, 21]])

In [100]:
a[[1, 2], [1,2]]

array([16, 21])

### (3) 조건 조회

- **조건에 맞는 요소를 선택**하는 방식이며, **불리안 방식**이라고 부릅니다.
- 조회 결과는 **1차원 배열**이 됩니다.

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

[문1] 다음 배열에서 80 미만의 데이터만 추출하시오.

In [101]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

In [102]:
score[score < 80]

array([78, 65, 79, 73])

[문2] 다음 배열에서 짝수만 추출해 보세요.

In [104]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 짝수만 조회
score[score % 2 == 0]


array([78, 84, 82, 96])

## 5.복습문제


1) numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [3]:
# 라이브러리 불러오기
import numpy as np


2) 다음 형태를 갖는 2차원 배열을 만들어 np_arr 변수로 선언하세요.

In [4]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

# 배열 만들기

np_arr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# 확인
print(np_arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


3) shape 속성을 사용해 np_arr 배열의 행과 열의 크기를 확인하세요.

In [18]:
# 배열 크기 확인
print(np_arr.shape)

(3, 3)


4) np_arr 배열을 아래 주어진 3 X 4 형태의 배열로 바꿔서 np_02 배열로 선언하고 확인하세요.

In [20]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# np_arr = np.array([[ 1,  2,  3,  4],
#                    [ 5,  6,  7,  8],
#                    [ 9, 10, 11, 12]])

# 형태 변경
np_02 = np_arr.reshape(3, 4)

# 확인
print(np_02)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


5) np_arr 배열의 세 번째 행의 요소들을 조회하세요.

In [24]:
# [7 8 9] 조회
print(np_arr[2, ])

[7 8 9]


6) np_arr 배열의 모든 요소에 10을 곱한 결과를 조회하세요.

In [25]:
# 10 곱하기
print(np_arr * 10)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


7) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.  
[ 8  9 10 11 12]

In [28]:
# 조건 조회
np_arr[np_arr >= 8]

array([ 8,  9, 10, 11, 12])

8) 7번 실습에서 선택된 요소들의 값만 각각 2배로 만드세요.

In [29]:
# 조회 결과에 대한 연산
np_03 = np_arr[np_arr >= 8]

np_03 *= 2

print(np_03)

[16 18 20 22 24]


9) np_arr 배열의 값을 조회해서 변경된 내용을 확인해 보세요.

In [30]:
# 원본 배열 확인
print(np_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


10) np_arr 배열의 요소들 중에서 3의 배수는 1, 아니면 0인 배열을 만들고 조회하시오.

In [31]:
arr = np.where(np_arr % 3 == 0, 1, 0)

print(arr)

[[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


11) np_arr의 전체 평균, 열별 평균, 행별 평균을 구하세요.

In [34]:
arr_mean = np.mean(np_arr)
# arr_mean = np_arr.mean()
arr_mean_a = np.mean(np_arr, axis=0)
# arr_mean_a = np_arr.mean(axis=0)
arr_mean_b = np.mean(np_arr, axis=1)
# arr_mean_b = np_arr.mean(axis=1)

print(arr_mean)
print(arr_mean_a)
print(arr_mean_b)


6.5
[5.5 6.5 7.5]
[ 2.  5.  8. 11.]


# 추가 문제

In [5]:
np_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
# 추가 1
print(np_arr[3][1])
print(np_arr[3, 1])

11
11


In [14]:
# 추가 2
print(np_arr[0:, 1])
print(np_arr[:, 1])
# print(np_arr[:, :])

[ 2  5  8 11]
[ 2  5  8 11]


In [21]:
# 추가 3
print(np_arr[[1],])
print(np_arr[1:2])

[[4 5 6]]
[[4 5 6]]


In [24]:
# 추가 4
print(np_arr[2:4, 1:3])
print(np_arr[2:, 1:])
print(np_arr[2:][:, 1:])

[[ 8  9]
 [11 12]]
[[ 8  9]
 [11 12]]
[[ 8  9]
 [11 12]]


In [30]:
# 추가 5
np_arr[[1, 3, 2],[0, 1, 2]]

array([ 4, 11,  9])